### ISSUE TITLE
Apple silicon problem

### ISSUE THREAD

**Issue by Yquetzal** [igraph/python-igraph#428] opened 2021-07-16 14:09 UTC
Hi,
I just switched to an apple silicon Mac, and cannot get igraph to work.
What I do: 
```
pip3 install python-igraph
```

which says:
```
Collecting python-igraph
  Using cached python_igraph-0.9.6-cp39-cp39-macosx_11_0_arm64.whl (373 kB)
Requirement already satisfied: texttable>=1.6.2 in /opt/homebrew/lib/python3.9/site-packages (from python-igraph) (1.6.4)
Installing collected packages: python-igraph
Successfully installed python-igraph-0.9.6
```

But then when I try to import igraph in python:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so, 2): Symbol not found: _igraph_eit_destroy
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
```

**Comment by Yquetzal** [comment] 2021-07-16 14:23
Additionally, when I try to compile from source, I get the following error:
```
❯ python setup.py build --use-pkg-config
  File "setup.py", line 465
    raise RuntimeError(f"Failed to clean {folder} with git")
                                                                                           ^
```
and this one I don't understand...

**Comment by Yquetzal** [comment] 2021-07-16 14:40
Note that after some initial difficulties, I managed to compile it from sources

**Comment by ntamas** [comment] 2021-07-20 09:36
Sorry for the late reply. Even if you managed to compile it from source, this is still worth investigating. Unfortunately I don't have an Apple Silicon Mac at hand so I can only guess; could it have been the case that you had other versions of the _C core_ of igraph installed on your machine when you initially tried the wheel? For instance, the one from Homebrew (which you can obtain with `brew install igraph`)?

Also, if you've had any other difficulties when compiling from source that you think should be fixed, please let me know.

**Comment by Yquetzal** [comment] 2021-09-20 15:37
Sorry I did not reply since It is difficult to investigate the problem, since I should be certain to start from a clean configuration again. 
What I can say is that it works with my manually compiled version, but if I create a virtuel environment with venv, which inherits global packages, then I have the broken version of igraph in it. And yes it is possible that I have done a `brew install igraph` before, I do not remember. I can make a few experiments if you want, otherwise the problem is solved for me since I've found a solution :)

**Comment by brimg** [comment] 2021-09-22 22:33
I am experiencing this problem currently.  What can I provide to help debug it?  I have tried installing and removing `igraph` using `brew`, neither configuration seems to work.

```
 python
Python 3.9.7 (default, Sep  3 2021, 04:31:11)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import igraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.9/site-packages/igraph/__init__.py", line 26, in <module>
    from igraph._igraph import (
ImportError: dlopen(/opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so, 2): Symbol not found: _igraph_eit_destroy
  Referenced from: /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
  Expected in: flat namespace
 in /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
```

It's the same error whether I have installed via `brew`.

Thanks!

**Comment by Yquetzal** [comment] 2021-09-23 07:13
If you want to use the same non-ideal but working solution than me, you have to follow the "compiling from source" section of the documentation...

**Comment by brimg** [comment] 2021-09-23 14:22
@Yquetzal Thanks for the suggestion, but that didn't work for me.  I'm hoping the `brew` + `pip` method gets fixed so we can port `igraph` usage between machines.

**Comment by ntamas** [comment] 2021-09-24 10:00
@brimg Let's start with posting what you get when you run the following commands:

```sh
$ otool -L /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
$ file /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so
$ nm /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so | grep igraph_eit
```

**Comment by kopeckyf** [comment] 2021-09-25 09:48
Hello everyone, 

I hope you don't mind me chiming in on this issue. I see exactly the same error message as OP and @brimg. @ntamas, I'm seeing this output for the commands you mentioned:

```shell
$ otool -L /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so

/opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so:
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```
```shell
$ file /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so

/opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so: Mach-O 64-bit bundle arm64
```
```shell
 $ nm /opt/homebrew/lib/python3.9/site-packages/igraph/_igraph.cpython-39-darwin.so | grep igraph_eit
                 U _igraph_eit_create
                 U _igraph_eit_destroy
```

**Comment by ntamas** [comment] 2021-09-25 17:59
I borrowed an Apple Silicon machine from my wife and I can confirm that the problem indeed exists with a stock installation. I'll check the build logs to figure out what goes wrong in the CI environment where the wheels are built.

**Comment by ntamas** [comment] 2021-09-27 09:12
Okay, I think I know what's going on. The CI system caches the compiled C core of igraph and tries to link to an x86_64 version of the C core when compiling the Apple Silicon version, and obviously it doesn't work. I'll need to figure out how to cross-compile to Apple Silicon on a non-M1 Mac because the CI systems do not support Apple Silicon natively yet.

**Comment by brimg** [comment] 2021-09-27 14:12
I have to say, it's amazing that you were even able to find that.   Thanks so much for getting at least this far.

**Comment by ntamas** [comment] 2021-09-29 09:35
There are new wheels in the output of [this CI run](https://github.com/igraph/python-igraph/runs/3736231150). You need to download the build artifacts, unzip them and install the apppropriate wheel manually with `pip install`. I'm not sure whether they work -- all I did was to cross-compile the C core of igraph in CI for Apple Silicon and then build the wheels as usual with `cibuildwheel`. The difference is that the size of the Apple Silicon wheel is closer to the non-SIlicon wheel and that `nm` does not list any igraph-related unlinked symbols from the generated `.so` file in the wheel, but I still haven't had the chance to test the wheels. It would be great if someone could try the wheels and report whether it is at least possible to import the wheel. If the import works, the output of `python -m unittest tests/` (executed from the source tree of `python-igraph`) would also be helpful.

**Comment by Yquetzal** [comment] 2021-09-30 07:28
I tried to do it but I'm not sure I'm doing it right.
Since I have a working version I compiled myself, I try to work with a virtual env. I checked that first I could not import `igraph` in it, then I downloaded the wheels on your link, run pip install on it. It seems to work: after that I can import `igraph` in my venv.

But when I try to run the tests: 
`======================================================================
ERROR: tests/ (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests/
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests/'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
` 

I tried to run it from several locations from the source of the package to `artifact/python-igraph-0.9.6/src/igraph` since I'm not sure which one is the source tree, but results were always the same.
I'm no expert in python packages so feel free to ask me to check something else.

**Comment by ntamas** [comment] 2021-09-30 08:38
Sorry, I have forgotten that the source tree now uses `pytest` so the full process is a bit more complex. If you use a virtualenv, you need to do something like this:

```
path-to-your-virtualenv/bin/pip install pytest
git clone https://github.com/igraph/python-igraph
cd python-igraph
path-to-your-virtualenv/bin/pytest tests
```

**Comment by Yquetzal** [comment] 2021-10-01 07:41
Here is the result:
```
=========================================================== test session starts ============================================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/remycazabet/Downloads/artifact/python-igraph-0.9.6/src/igraph/python-igraph
collected 422 items                                                                                                                        

tests/test_atlas.py .........                                                                                                        [  2%]
tests/test_attributes.py ..............................                                                                              [  9%]
tests/test_basic.py ......................................                                                                           [ 18%]
tests/test_bipartite.py ........                                                                                                     [ 20%]
tests/test_cliques.py ............                                                                                                   [ 22%]
tests/test_colortests.py ...........                                                                                                 [ 25%]
tests/test_conversion.py .........                                                                                                   [ 27%]
tests/test_decomposition.py ....................................                                                                     [ 36%]
tests/test_edgeseq.py ................................                                                                               [ 43%]
tests/test_flow.py .................                                                                                                 [ 47%]
tests/test_foreign.py ....s....s.....                                                                                                [ 51%]
tests/test_games.py ...........                                                                                                      [ 54%]
tests/test_generators.py .................                                                                                           [ 58%]
tests/test_homepage.py ....                                                                                                          [ 59%]
tests/test_indexing.py ....                                                                                                          [ 59%]
tests/test_isomorphism.py ...........                                                                                                [ 62%]
tests/test_iterators.py .....                                                                                                        [ 63%]
tests/test_layouts.py ......................                                                                                         [ 68%]
tests/test_matching.py .....                                                                                                         [ 70%]
tests/test_operators.py ...............................                                                                              [ 77%]
tests/test_rng.py ...                                                                                                                [ 78%]
tests/test_separators.py .....                                                                                                       [ 79%]
tests/test_spectral.py ..                                                                                                            [ 79%]
tests/test_structural.py ................................................                                                            [ 91%]
tests/test_unicode_issues.py ..                                                                                                      [ 91%]
tests/test_vertexseq.py .............................                                                                                [ 98%]
tests/test_walks.py ......                                                                                                           [100%]

===================================================== 420 passed, 2 skipped in 12.17s ======================================================
```

**Comment by ntamas** [comment] 2021-10-01 15:42
Looks good to me - the wheels seem to be okay! A new release is coming soon so I'm closing this and I will publish new wheels once the new release is out.

**Closed by ntamas** 2021-10-01 15:42 UTC
Labels: bug
