### ISSUE TITLE
DotError when reading igraph dot file containing the word 'Node' in the label

### ISSUE THREAD

**Issue by dpdoughe** [igraph/python-igraph#135] opened 2017-08-23 17:25 UTC
Note this issue is possibly duplicate with https://github.com/pygraphviz/pygraphviz/issues/134.
The bug may be in python-igraph or pygraphviz depending on the .dot file format specification.

Pygraphviz fails to create a graph from a .dot file using AGraph when the node label contains the word 'Node' raising a DotError exception.  This may be a bug in python-igraph write_dot method (failing to quote all labels) depending on .dot file format conventions.

Here is a SSCCE of the problem:

import igraph
import pygraphviz as pgv
import tempfile

tmp = tempfile.NamedTemporaryFile(delete=True)
g = igraph.Graph.Tree(7, 2)

g.vs['label']='Node'
g.write_dot(tmp.name)
G=pgv.AGraph(tmp.name) # The DotError happens here

**Comment by dpdoughe** [comment] 2017-08-23 17:31
If write_dot quoted all label strings this may fix the issue. See https://github.com/pygraphviz/pygraphviz/issues/134 for several failure modes.

**Comment by ntamas** [comment] 2017-09-06 20:18
It is (or well, _was_) a bug in igraph's `write_dot` method; there is a statement in the [DOT specification](http://www.graphviz.org/doc/info/lang.html) that says:

> Obviously, to use a keyword as an ID, it must be quoted.

It has been fixed in https://github.com/igraph/igraph/commit/1bc4a2b77ffa4ab40eaf96ff84abe70fcdd04b28, but there was no new release of the C core since the fix so you need to compile the master branch of the C core as well as the master branch of the Python interface manually to work around this.

Duplicate of https://github.com/igraph/igraph/issues/959

**Closed by ntamas** 2017-09-06 20:18 UTC
