### ISSUE TITLE
Link to the API reference is broken

### ISSUE THREAD

**Issue by lorenzobn** [igraph/python-igraph#573] opened 2022-09-24 15:17 UTC
Hello everyone!

This is the first time I am writing here, so please apologize if I am in the wrong place.

**Describe the bug**
It's about the website and the docs. I was looking for the latest API reference. Clicking on the link in the website, it returns a "Page not Found" error.

**To reproduce**
1) Go here: [https://igraph.org/python/tutorial/latest/](https://igraph.org/python/tutorial/latest/)
2) Under the "Reference" menu, click on "API reference"
3) You'll get a Page not found error.

Or, you could directly click on this link: [https://igraph.org/python/tutorial/latest/api/index.html](https://igraph.org/python/tutorial/latest/api/index.html)

**Version information**
Latest version: 0.10.1

**Comment by ntamas** [comment] 2022-09-24 18:06
Thanks for the report!

@iosonofabio This actually indicates a deeper problem with the generated documentation; basically, whenever we refer to the API docs from the "main" docs, it seems like we assume that `api/` is a subfolder of `tutorial/`, which is not the case when the site is deployed with Jekyll. I can start sorting this out some time next week, but this is like the millionth HTML-rewrite hack that we need to add to the documentation generation pipeline to keep things together; there must be a better solution. If you have any ideas about how to improve this in the long run, let me know!

**Comment by iosonofabio** [comment] 2022-09-24 21:26
Agreed: readthedocs would be the way to go if possible.

**Comment by iosonofabio** [comment] 2022-09-24 21:32
@ntamas let me take this one anyway: it has to do with a quirk of the API parser I believe, shouldn't take me long

**Comment by iosonofabio** [comment] 2022-09-25 01:06
Ok, if I just git pulls `master` and runs `scripts/mkdoc.sh -j` I get a bunch of docstring errors, additionally the api reference link is broken.

I'll investigate the cause for both the errors and the breakage now. @ntamas: this script should run flawlessly before we make a new release to avoid situations like the current one. Any place where you could put a note about that since you're the one practically making the releases? Perhaps we should add this to CI?

**Comment by iosonofabio** [comment] 2022-09-26 20:22
Just a quick heads up.

I found how to repair the broken link here and found several other ones and fixed them too. The nice thing about how we build the docs in the `igraph.org` repo is that we can hotfix old versions post facto. Therefore, I'm spending a little more time to make the docbuilding more sustainable in the future.

1. `pydoctor` as it stands now requires the API docs to be in a subfolder of the main docs: tried to free ourselves from that constraint in the past and ran into a series of micro-bugs in their codebase. On the flip side, it would be actually better to have both API and tutorials in one place for us. So I'm now moving the python docs from `0.10` onwards to a unified location `/python/versions/xxx`, with the API of the same version going into `/python/versions/xxx/api`.

2. I'm also eliminating the landing page `/python/index.html` and pointing the link on the main website directly to `/python/versions/latest/index.html`: that had been bothering me for such a long time.

3. In terms of build process, I moved to a single `py_postprocess_html.py` script instead of separate ones for API and tutorials. This still does the right thing for older versions `<0.10` but greatly simplifies the logic for current and future versions. Together with that, one has to adapt Jekyll templates, related JavaScript, etc. but I'm optimistic this can all be sorted out within a few days.

4. The latest docs themselves are still a little buggy because `pydoctor` does not support all `epydoc` tags (e.g. `attention`, `newfield`). It's an open issue on their repo, but it seems to be unlikely this is fixed in the immediate future. Perhaps we could ask them.

In terms of long-term maintenance, I would love to have the python docs on readthedocs.org. It's what many other projects do, and it would look more "pythonic". However, that can realistically happen only after we stop supporting docs from versions `<0.10` because those require all kinds of quirks to build that readthedocs won't like. Once I'm done with this I'll take a look at that option. For now, having a single building process via Sphinx and a single postprocess script for Jekyll is not such a terrible situation AFAICT.

**Comment by ntamas** [comment] 2022-09-27 21:05
@iosonofabio sorry for the late reply, I've had classes on Monday and today and I needed to set some time aside to investigate this as well. (And I'm afraid that it's a bit hard now to find a time window where both you and me are awake so we'll probably have to roll with async communication). Here are my thoughts:

1. Yes, readthedocs is the way to go if we can massage the documentation into a format that's okay with them. I have given up now on the idea of making python-igraph's doc fit with the styling of the main homepage, it just causes more and more problems down the line, and at some point we should just let it go and let the docs live at readthedocs if we can make it work.
2. Moving the docs is okay for me, although it seems like a quirk of `pydoctor`. Conceptually, in my head, there's a tutorial and there are the API docs and they both stand on the same hierarchical level, with maybe a unified landing page that leads to one or the other.
3. Can we keep using `pydoctor` if we decide to move to readthedocs or does it have its own tooling? If so, maybe they don't have this limitation about the API docs being a strict subpage of the tutorial.
4. It's unclear to me what the next steps are now. I'd love to help but I don't want to step on your toes either, so I'd just say that if you need any help with this, drop me a message and let me know what needs to be done.
5. Testing the doc build in CI is a good idea, but then we need a way to clearly identify if the docs are broken. `pydoctor` output generates lots of harmless warnings now due to the unsupported Epydoc tags. I think the `@newfield` tag is not likely to be supported any time soon as it's basically only Epydoc that supports this construct, and there are only a few instances of `@attention` so we can probably get rid of both. `@newfield` is used only to provide literature references, but for me it seems like it's not very common in Python docs to include literature references anyway, and people who care about these types of things can probably look up the references in the C docs anyway, so I'm slightly leaning towards removing them completely. If we do so, then we probably need to run a link checker in CI on the generated docs to see if there are any broken internal links. Anything else that should be done here?

**Comment by iosonofabio** [comment] 2022-09-27 21:08
@ntamas thank you for your answer. No need from the input at this stage: I have it working on my machine, will make a PR later today.

Long term, let me experiment with readthedocs a little bit.

**Comment by iosonofabio** [comment] 2022-09-28 11:44
Just pushed the PR which fixes this and a bunch of other bugs in the docs.

Since we are on the topic, I am planning the following improvs for the python docs:

- Jupyter notebook examples using sphinx-gallery
- a few long tutorials covering distinct scientific disciplines
- translation into Spanish

All of those are on my radar, so stay tuned.

**Comment by szhorvat** [comment] 2022-09-28 14:20
> * Jupyter notebook examples using sphinx-gallery
> 
> * a few long tutorials covering distinct scientific disciplines

Very nice!

> * translation into Spanish

Will you do this yourself, or will you hire someone?

Once concern is ending up with outdated translations that we are unable update. Do you have a plan to deal with this? For example, keep it in a form that makes it very easy for users to submit correction (best is probably a wiki, next-best is something that's editable using GitHub's online interface)

**Comment by iosonofabio** [comment] 2022-09-28 20:25
I have already hired someone 😋

We'll try with a pilot in which they translate a few tutorials only and I set up a branch of the repo that includes the html to show little flags and whatnot.

Outdated docs are indeed the concern. My plan is to run a diff on the English docstring and it's nonempty display a banner in Spanish that says "this function might have changed, check the English docs _here_". But it's purely experimental for now, open to suggestions!

**Comment by ntamas** [comment] 2022-09-29 08:30
Also, if we plan to migrate to readthedocs in the near future, I was wondering whether it would be possible to put one of those "Edit this page on Github" buttons on the doc pages? Ideally, the button would open Github's editor interface with the appropriate source file and then anyone could easily make a PR with doc fixes without having to clone the repo.

**Comment by iosonofabio** [comment] 2022-09-29 08:34
Happy to look into it

**Comment by ntamas** [comment] 2022-09-30 10:36
The links on the homepage should now be fixed, although not all old links might be valid any more as we have reshuffled things a bit since 0.10. Please try accessing the API docs from https://igraph.org/python/; it should be okay now. Feel free to reopen if this is still not the case.

**Closed by ntamas** 2022-09-30 10:36 UTC
