### ISSUE TITLE
GraphBase.get_eids() does not have argument "path"

### ISSUE THREAD

**Issue by alejandrocca** [igraph/python-igraph#601] opened 2022-10-20 21:26 UTC
Latest documentation for [python-igraph](https://igraph.org/python/versions/latest) 0.10.1 says parameter "path" should exist:
https://igraph.org/python/versions/latest/api/igraph.GraphBase.html#get_eids

Inspection of the function as following:

inspect.getargspec(GraphBase.get_eids)
ArgSpec(args=['pairs', 'directed', 'error'], varargs=None, keywords=None, defaults=(None, True, True))

**Comment by ntamas** [comment] 2022-10-20 21:58
Duplicate of #581

**Closed by ntamas** 2022-10-20 21:58 UTC
