### ISSUE TITLE
Plot display consistently fails on Linux after writing glitchy code, even when using fixed or new code.

### ISSUE THREAD

**Issue by will-ca** [igraph/python-igraph#173] opened 2018-05-14 20:07 UTC
---
### Run code:
```
import igraph
(lambda g: igraph.plot(g, layout=g.layout('kk')))(igraph.Graph.Tree(127,2))
```

### Result:
![screenshot from 2018-05-14 12-26-34](https://user-images.githubusercontent.com/37680486/40018812-3863e624-5772-11e8-9f4a-2e8d8726b38b.png)
---
I had a project where I constructed Igraph graphs to visualize information stored in my own objects. At one point, changes to acceptable data types in how my objects are constructed led to code that attempted to construct `igraph.Graph` objects in ways that would invariably (and obviously) produce errors.
For example:
* Adding a vertex with a numbered name that had been converted to a string but then later attempting to associate edges by referencing the original integer value.
* Attempting to assign `igraph.Graph().vs['label']` with a list comprehension that itself would raise an exception due to attempting to access information incorrectly from my original object.
* Adding vertices with integer names that had been produced by Python's `hash(time.time())` function, which were too large for the C backend.
These all raised exceptions and prevented my code form progressing to the point where the plot would be rendered, as is to be expected.

However, even after fixing/reverting my original code and testing fresh plots with graphs generated by `igraph.Graph`, the plot still fails with the above behaviour where it worked perfectly before.

---
The workaround detailed at [this StackOverflow link](https://stackoverflow.com/questions/22934342/no-image-from-plot-in-igraph-python) works for getting the plot to show, but required refactoring a bit of code and further work to preserve attractive layout settings.
Aside from the workaround, I also got a single successful plot to display by making a single `.py` file with only `import igraph` in it, running it as an interactive Python session, and pasting the above code into it. As of now, however, all attempts to run the above code produce the same error whether they are read from a file, partially read from a file, or inputted entirely from within an interactive session.
Information about my Python environment and Igraph installation is provided below:
```
$ python3
Python 3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)] on linux
$ pip3 show python-igraph
Name: python-igraph
Version: 0.7.1.post6
Summary: High performance graph data structures and algorithms
Home-page: http://pypi.python.org/pypi/python-igraph
Author: Tamas Nepusz
Author-email: tamas@cs.rhul.ac.uk
License: GNU General Public License (GPL)
Location: /home/Will/.local/lib/python3.6/site-packages
Requires: 
```

**Comment by ntamas** [comment] 2020-01-30 09:58
This is probably worth investigating before the next milestone - thanks for the report.  We'll look into this.

**Comment by iosonofabio** [comment] 2020-07-14 03:18
Hmm, this is what happens on my linux (Arch, with `python-cairo` available from pacman):

```bash
[~]$ ipython
Python 3.8.3 (default, May 17 2020, 18:15:42) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import igraph; (lambda g: igraph.plot(g, target='/tmp/test.png', layout=g.layout('kk')))(igraph.Graph.Tree(127,2))                       
Out[1]: <igraph.drawing.Plot at 0x7f28029bfd00>
```

and the file looks just fine:

![test](https://user-images.githubusercontent.com/1200640/87379646-1ab48c00-c5d4-11ea-8448-a7efbabe06b9.png)

If I call the code from the command line it also works (swapping single quotes for doubles for convenience):

```bash
python -c 'import igraph; (lambda g: igraph.plot(g, target="/tmp/test2.png", layout=g.layout("kk")))(igraph.Graph.Tree(127,2))'
```

(same image, no need to reshow it here).

So I'm not sure what's wrong with @will-ca 's installation but I cannot reproduce. I propose we close this.

**Comment by ntamas** [comment] 2020-07-14 09:57
Does `python-igraph` automatically open an image viewer for you or are you just simply checking the output file by opening an image viewer manually? The Python interface has this feature (which I have come to regret after a while) that when you call `plot()` without a filename, it tries to find an appropriate image viewer on your system, plot the graph to a temporary file, pass the temporary file to the image viewer, and then remove the file. The issue mentioned in the post sometimes happens when the temporary file is removed _before_ the image viewer gets a chance to open it. (There is even a nasty hack with `sleep()` somewhere to prevent this).

So, this issue is most likely platform specific and probably even depends on the specific image viewer that igraph happens to detect.

**Comment by iosonofabio** [comment] 2020-07-14 23:30
I save it to file and open it separately.

I've had many programs try to get that kind of stunt right on Linux and it doesn't really work *except* if you open the image in a browser, because:

- everyone has a browser
- there are 3/4 browsers that 99.9% of users will have, anyone else is a power user anyway
- browsers can read SVG just fine

I am not even sure we need to remove the file. If it's a temp file, the OS will take care of it sooner or later.

If you are wondering my own opinion, I'd just kill the feature and leave no regrets.

**Comment by ntamas** [comment] 2020-07-16 20:14
> browsers can read SVG just fine

I wish it had been that way when I originally added this feature -- this was back in those days where IE was the dominant browser and most browsers had poor or nonexistent SVG support.

> I am not even sure we need to remove the file. If it's a temp file, the OS will take care of it sooner or later.

Yeah, I just don't like leaving random stuff around and hope that someone else cleans up my mess :)

Anyway, you are probably right, I should probably simply mark this feature as deprecated in the next minor release and then get rid of it by 1.0 or so.

**Comment by ntamas** [comment] 2021-03-10 13:29
Calling `plot()` without a filename is now deprecated in 13e0436. The feature will be removed in 0.10.0 or 1.0.0, whichever comes first.

**Closed by ntamas** 2021-03-10 13:29 UTC
Labels: bug, todo

**Comment by ntamas** [comment] 2021-03-10 13:38
`plot()` returns an object of type `Plot`, which has a magic method named `_repr_svg_()` that provides an SVG representation. Jupyter uses that to show the plot. In `plot()` we actually check whether we are running inside Jupyter / IPython and we don't invoke the default image viewer there.

The deprecation warning is added to the `show()` method of the `Plot` object, which is indeed called only when we attempt to create a temporary file and show that with the default image viewer.
