### ISSUE TITLE
Warnings have the full path of source files

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#293] opened 2020-04-30 18:40 UTC
I'm opening this issue here because I do not see the same problem with the Mathematica interface, so it might have to do with the build settings for the Python one.

When igraph issues a warning, it references a line of a source file. This is good, but what it seems to do is to include the absolute path of the source file. That is too much, and may contain information it shouldn't (depending on how igraph was built).

Transcript:

```
In [1]: from igraph import *                                                    

In [2]: g=Graph.Erdos_Renyi(10, 0.1, directed=True, loops=False)                

In [3]: print(g)                                                                
IGRAPH D--- 10 10 --
+ edges:
6->0 6->2 4->3 0->4 7->5 5->6 6->9 3->7 8->7 1->8

In [4]: g.is_dag()                                                              
Out[4]: False

In [5]: g.topological_sorting()                                                 
<ipython-input-5-b8d21865468c>:1: RuntimeWarning: graph contains a cycle, partial result is returned at /private/tmp/pip-req-build-26_qaoq3/vendor/source/igraph/src/structural_properties.c:3448
  g.topological_sorting()
Out[5]: [1, 8]
```

This is on macOS.

**Comment by ntamas** [comment] 2020-04-30 19:49
I guess it's simply a matter of setting up the warning handler differently in `src/_igraph/error.c`; we simply show the filename that igraph passes to us. `igraph` takes it from the `__FILE__` constant during compilation.

I can remove it from the warning handler so it only shows the warning message and nothing else.

**Comment by szhorvat** [comment] 2020-04-30 19:49
I'm puzzled. The file name should ultimately come from the `__FILE__` macro of the compiler:

https://github.com/igraph/igraph/blob/master/include/igraph_error.h#L715

I assume that the Python interface is compiled with clang on macOS. I use clang for the Mathematica interface. There should be no difference.

Why do we get the full path in one case but not the other?

**Comment by szhorvat** [comment] 2020-04-30 19:51
@ntamas We commented at the same time. 

I just double-check the code I use for the Mathematica interface, and it does not manipulate the file name in any way. It prints directly whatever comes from `__FILE__`. And it looks like this:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/1212871/80752936-b5044800-8b2c-11ea-8653-c485760fffed.png">

No full path.

There must be something that causes `__FILE__` to expand to  the full filename, perhaps it has to do with which directory the compiler is invoked in?

**Comment by ntamas** [comment] 2020-04-30 19:53
I think that if you invoke the compiler with an absolute path, then `__FILE__` will be absolute, otherwise it will be relative. In both cases, it will most likely simply reproduce the path that you passed to the compiler when compiling the file.

**Comment by szhorvat** [comment] 2020-04-30 19:57
> I think that if you invoke the compiler with an absolute path, then `__FILE__` will be absolute,

Yes, that is correct. I just did a quick test with

```
#include <stdio.h>

int main() {
    printf("%s", __FILE__);
    return 0;
}
```

Indeed, it prints the path that was passed to the compiler.

**Comment by ntamas** [comment] 2020-04-30 20:11
Okay, so it looks like we either shorten the path at runtime (which means that the filename still leaks into the compiled binary of the library), or we need to force `pip` somehow to use relative filenames when compiling the C library. Let me check whether there's an easy fix for this in `setup.py`.

**Comment by vtraag** [comment] 2020-04-30 20:11
> I can remove it from the warning handler so it only shows the warning message and nothing else.

It is a bit annoying that it prints the absolute path (which might also contain somewhat more sensitive information), but I think we should still print it, as it might make it easier to track down some possible bugs.

> if you invoke the compiler with an absolute path, then __FILE__ will be absolute, otherwise it will be relative. 

The question is then whether we can change `setup.py` so that it compiles without using absolute paths. I'm not exactly sure why it ends up using absolute paths, but perhaps this line is to blame for that?

https://github.com/igraph/python-igraph/blob/dee73ba0a5141047453718e4c9b1e75f08a2244f/setup.py#L300

**Comment by ntamas** [comment] 2020-04-30 20:22
I think what happens is that we are essentially doing an out-of-source-tree build during the compilation process, so we change the current working directory to the build folder and then invoke the configure script _from the source folder_, with its full absolute path. The `./configure` script then figures out how to refer to the source folder from the build folder so it can invoke `gcc`, and this is where the full path gets injected.

On my machine, when I am compiling igraph from C, I also tend to use a separate build folder (named `build`, within the source tree). When doing so, `gcc` gets invoked like this at build time:

```
gcc -DHAVE_CONFIG_H [...yaddayaddayadda...] -c ../../src/structural_properties.c  -o .libs/libigraph_la-structural_properties.o
```

Note the usage of _relative_ paths; basically, `gcc` is invoked in `$build_dir/src`, and it needs a source file from `$source_dir/src`, so it needs to step up twice (`../../`) to the source tree, and then down to `src`. This is what also gets included in the library, e.g.:

```
$ strings build/src/.libs/libigraph_la-cocitation.o
../../src/cocitation.c
invalid vertex ID in vertex selector
number of elements in `pairs' must be even
cannot calculate Jaccard similarity
```

So, it looks like the only way to avoid any sort of extra path segments is to do an in-tree build. We can probably get around with a few extra `../..` if we create the build folder near the source folder (e.g., in `vendor/build`).

**Comment by ntamas** [comment] 2020-04-30 20:33
This is what I managed to come up with; it will use `../../../igraph/src/whatever.c` in warning messages. I guess that's the best we can do without doing an in-tree build.

**Closed** 2020-04-30 21:10 UTC

**Comment by szhorvat** [comment] 2020-04-30 21:27
I might look into contributing some simple C code that dynamically removes any ../../../ before printing the message.

**Comment by szhorvat** [comment] 2020-04-30 21:33
In the MacPorts version, the full path looked pretty awful:

```
<stdin>:1: RuntimeWarning: graph contains a cycle, partial result is returned at /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_python_py-igraph/py38-igraph/work/python-igraph-0.8.2/vendor/source/igraph/src/structural_properties.c:3448
```

**Comment by ntamas** [comment] 2020-04-30 22:27
> I might look into contributing some simple C code that dynamically removes any ../../../ before printing the message.

That would be great -- feel free to send a PR when you have something. (Although at that point we could even do it in the C core, before the filename is sent to the warning handler).
