### ISSUE TITLE
Error in py_module_import(module, convert = convert) :  AttributeError: module 'igraph' has no attribute 'VertexClustering'

### ISSUE THREAD

**Issue by Rui-Jing** [igraph/python-igraph#458] opened 2021-11-15 00:56 UTC
Hi,
Thanks for developing this powerful tool. I meet a problems when I used **InfercnV (a R package)** to process the Single-cell data in R.

**Describe the bug**
Error in py_module_import(module, convert = convert) : 
  AttributeError: **module 'igraph' has no attribute 'VertexClustering'**

**To reproduce**
This software (**infercnv**) error occurs in step 15 :computing tumor subclusters via leiden.

If you are unsure, feel free to add your issue here - we will transfer it to
the main [igraph repo](https://github.com/igraph/igraph) if the root cause is
in the C core of igraph.

**Version information**
**igraph**             0.9.8（**linux**）
leidenalg         0.8.8  (**linux**)
**igraph**             1.2.8   (**R package**)

**Comment by ntamas** [comment] 2021-11-15 09:54
Can you point me to the part in the `infercnV` source code where it tries to import `VertexClustering` from `igraph`? It does not seem to be an issue with `python-igraph` itself because `VertexClustering` can be imported just fine in a vanilla Python environment:

```
>>> from igraph import __version__, VertexClustering
>>> __version__
'0.9.8'
>>> VertexClustering
<class 'igraph.clustering.VertexClustering'>
```

**Comment by szhorvat** [comment] 2021-11-15 10:02
@ntamas  I think it uses this package: https://cran.r-project.org/web/packages/leiden/index.html @vtraag is also an author of that package. @vtraag, is that package now obsolete considering that we have `cluster_leiden` in R/igraph 1.2.8?

**Comment by vtraag** [comment] 2021-11-15 13:52
> @ntamas I think it uses this package: https://cran.r-project.org/web/packages/leiden/index.html @vtraag is also an author of that package.

That package is not mine, but by @TomKellyGenetics. It provides an R wrapper around my Python `leidenalg` package. That package is more extensive than the current implementation in `igraph`.

Perhaps @TomKellyGenetics may weigh in on this error though, as it probably relates to the interfacing between the packages somehow, not to `python-igraph` itself.

**Comment by TomKellyGenetics** [comment] 2021-11-16 09:16
Sorry for the confusion. I developed the R interface to Python leidenalg using reticulate. I gave @vtraag credit as the author of the Python module doing the actual computations.

However, I wasn't involved in this package at all but it does appear to depend on “leiden” not “igraph”. https://github.com/broadinstitute/infercnv/blob/master/DESCRIPTION 

If there is an issue with that package please report it there. If the issue is from the R package please reproduce the issue by calling it directly and report it here. https://github.com/TomKellyGenetics/leiden/issues

To be clear, the R version of “leiden” on CRAN doesn’t call the new functions in r-igraph yet but the “dev” branch does. @vtraag As we have discussed before I will test the dev version before merging and pushing to CRAN. Thanks for your efforts on this. I have started a new job and am moving house so sorry this me take me some time.
See here for details https://github.com/TomKellyGenetics/leiden/issues/1

**Comment by TomKellyGenetics** [comment] 2021-11-16 09:18
I recommend closing this issue and filing a new one with the relevant R package that is calling leidenalg with an incompatible Python igraph object. Thank you.

**Comment by vtraag** [comment] 2021-11-16 13:55
Thanks for the explanation @TomKellyGenetics! Good luck with your new job and moving. I'll close this issue for the moment then. @Rui-Jing , if it turns out that there somehow still is some problem with `python-igraph` feel free to come back and re-open the issue.

**Closed by vtraag** 2021-11-16 13:55 UTC

**Comment by szhorvat** [comment] 2021-11-16 13:57
I wonder if `infercnV` could just use `igraph` now instead of relying on `leiden`. Perhaps it doesn't use any features that are specific to `leiden`? Should we reach out to `infercnV` and suggest the change?

**Comment by vtraag** [comment] 2021-11-16 14:01
Yes, we could do that indeed. Let me open an issue in `infercnV`.
