### ISSUE TITLE
topological sorting

### ISSUE THREAD

**Issue by istvanftoth** [igraph/python-igraph#327] opened 2020-09-07 17:14 UTC
Make sure that these boxes are checked before submitting your issue -- thank you!

- [ x] This issue is for the Python interface of igraph.
- [x ] This issue is a bug report or a feature request, not a support question.

Hi, I would like to know the name or a reference to the algorithm, which was used in the topological_sorting() function of python-igraph. Specifically I would like to know the specific order of the nodes which do not have an incoming edge, but the documentation of python-igraph does not mention any references or algorithms.
Thanks very much,

**Comment by ntamas** [comment] 2020-09-07 18:35
Closing as this is a support question, not a bug report or a feature request. Next time please send support questions in the [discussion forum](https://igraph.discourse.group).

Regarding the original question: I don't think that this algorithm has a specific name; we simply keep on removing source nodes from the graph until there are either no more nodes or all the remaining nodes have at least one incoming edge (in which case the graph is not a DAG). There are no guarantees about the ordering of the nodes if there is more than one source node. The current implementation first puts all the source nodes in a queue in increasing order of node IDs and then starts processing the queue from the front; newly produced source nodes after edge removals are added to the end of the queue, but we reserve the right to change this any time.

**Closed by ntamas** 2020-09-07 18:35 UTC

**Comment by vtraag** [comment] 2020-09-08 07:03
For what it's worth, I think the algorithm is called [Kahn's algorithm](https://en.wikipedia.org/wiki/Topological_sorting#Kahn's_algorithm). The alternative DFS implementation may be slightly faster, so perhaps it makes sense to switch to that implementation at one point. Note that neither implementation guarantees anything about a particular ordering.
