### ISSUE TITLE
Graph.contract_vertices() combine_attrs parameter throws a segmentation fault

### ISSUE THREAD

**Issue by jfmalloy1** [igraph/python-igraph#358] opened 2021-01-19 20:54 UTC
The "first", "last", "random", and "median" parameters of the `combine_attrs` parameter in Graph.contract_vertices() all cause a segmentation fault, while the "min", "max", and "concat" parameters throw separate errors. "Sum", "product", and "average" all work as expected.

`G.contract_vertices(mapping, combine_attrs="first")` -> segmentation fault
`G.contract_vertices(mapping, combine_attrs="last")` -> segmentation fault
`G.contract_vertices(mapping, combine_attrs="random")` -> segmentation fault
`G.contract_vertices(mapping, combine_attrs="median")` -> segmentation fault
`G.contract_vertices(mapping, combine_attrs="min")` -> error, min() is an empty sequence
`G.contract_vertices(mapping, combine_attrs="max")` -> error, max() is an empty sequence
`G.contract_vertices(mapping, combine_attrs="concat")` -> error, cannot concat string + int (this may be a product of my code)
`G.contract_vertices(mapping, combine_attrs="sum")` -> works, attributes are summed
`G.contract_vertices(mapping, combine_attrs="product")` -> works
`G.contract_vertices(mapping, combine_attrs="mean")` -> works

Using 0.8.3 in Python3

**Comment by ntamas** [comment] 2021-01-21 13:48
Can you show me the contents of `mapping` and maybe the edge list of a small graph on which I could reproduce the issue? I tried this now on my machine and it works just fine:

```
>>> from igraph import Graph
>>> g=Graph.GRG(100, 0.2)
>>> mapping=[0]*50 + [1] * 50
>>> g.vs["name"] = [str(x) for x in range(100)]
>>> g2 = g.copy(); g2.contract_vertices(mapping, combine_attrs="first")
>>> g2.vcount(), g2.ecount()
(2, 512)
>>> g2.vs["name"]
['0', '50']
```

I suspect that there's something wrong with the `mapping` vector that you try to use; this should nevertheless not crash the Python extension so it's a genuine bug and I'd like to investigate further.

**Comment by jfmalloy1** [comment] 2021-01-21 20:42
Of course! Here's the test graph I'm using. I'm generating the mapping within the function itself, but since it works with sum, I imagine this isn't the issue?

`
import igraph as ig
num_nodes = 8
G = ig.Graph(num_nodes, directed=True)
G.vs["name"] = [x for x in range(num_nodes)]

#Incoporate edges
G.add_edges([(1,3), (1,4), (1,5), (1,7)])
old = [2, 3, 4]
center = 1
G.contract_vertices([center if x in old else x for x in range(G.vcount())], combine_attrs="first")
G.vs["name"]
`

**Comment by ntamas** [comment] 2021-01-22 21:58
I still suspect that the `mapping` is problematic; your code indeed crashes on my machine as well, but replacing `[0, 1, 1, 1, 1, 5, 6, 7]` with `[0, 1, 1, 1, 1, 2, 3, 4]` as the mapping seems to work.

I guess that the problem is the following. igraph has its roots in a C library where the node indices are consecutive integers from 0 to |V|-1. A mapping vector like `[0, 1, 1, 1, 1, 5, 6, 7]` therefore means that vertices 1, 2, 3 and 4 are collapsed into a single vertex 1, and vertices 0, 5, 6 and 7 are kept as they are, so igraph has to do something with vertices 2, 3 and 4 to keep the vertex index range contiguous. `collapse_vertices()` solves these by making vertices 2, 3 and 4 isolates. However, if they are isolates, then it is ambiguous what their `name` should be if you use `first`, `last`, `random`, `median`, `min` or `max`. There are reasonable defaults for `sum` (zero) and `product` (one). For `mean`, I think igraph also uses zero as the default, although it is arguable whether it is correct or not.

Anyway, this will be fixed soon now that I think I understand what the problem is.

**Comment by iosonofabio** [comment] 2021-01-23 01:20
Want me to take this one?

**Comment by ntamas** [comment] 2021-01-26 10:20
Hang on, I'm currently working on bringing the master branch up-to-date with 0.9. After that I'll probably tackle this on my own.

**Closed** 2021-01-26 15:38 UTC
