### ISSUE TITLE
Shortest circuit in a directed graph

### ISSUE THREAD

**Issue by Puumanamana** [igraph/python-igraph#526] opened 2022-04-11 21:58 UTC
Hello,

I am trying to compute the shortest circuit in a directed graph. I thought it would be straightforward by simply doing `graph.get_all_shortest_paths("A", "A")`, but this only returns the start vertex (even though there are no self edges in my case).

Example:
```python
g = Graph(directed=True)
g.add_vertices(list("ABC"))
g.add_edges(["AB", "BC", "CA"])
g.get_all_shortest_paths("A", "A")

Out: [[0]]
# Desired output: [[0, 1, 2]] or [[0, 1, 2, 0]]
```

I'm not sure if this behavior is a bug or simply a design choice. Would it be something easy to implement/fix?

Thank you!

**Comment by szhorvat** [comment] 2022-04-11 22:19
This is not a bug, but simply following the common understanding of shortest paths, which are all part of a shortest path tree. To reach `A` from `A`, you don't need to move at all: you are already there. The solution is a zero-length path, with no edges in it. If `A` had a self-loop, traversing that self-loop would induce a length-1 path, which is not as short as the zero-length one. Cycles are never shortest paths.

As for implementing finding shortest directed cycles, a BFS should work for that, but I'm not sure if igraph's `bfs` function is sufficiently flexible for that and I'm too tired to figure it out at this hour.

I will close this now, and since this is not a bug, I suggest continuing the discussion on the forum, https://igraph.discourse.group/

**Closed by szhorvat** 2022-04-11 22:19 UTC
