### ISSUE TITLE
Could not download and compile the C core of igraph

### ISSUE THREAD

**Issue by EmilyYanW** [igraph/python-igraph#159] opened 2018-02-06 20:35 UTC
I am using Mac 10.13 High Sierra and Python 3.6.3 :: Anaconda custom (x86_64). I tried both homebrew and easy_install but I keep getting error  "Could not download and compile the C core of igraph" (See screenshot below). 
When I use ./configure & make & make check & make install, it tells me the best matching igraph is "Best match: python-igraph 0.7.1.post6"
igraph is configured: 
![screen shot 2018-02-06 at 1 19 48 pm](https://user-images.githubusercontent.com/32230484/35884781-917bef82-0b40-11e8-96ef-a833c6276556.png)

And for the next step 'make" I got this:
![screen shot 2018-02-06 at 1 22 47 pm](https://user-images.githubusercontent.com/32230484/35884882-e8ba87b8-0b40-11e8-978d-7f572cbe8f1a.png)
And when I run "pip install python-igraph" in  my terminal, I got this: 
![screen shot 2018-02-06 at 1 34 16 pm](https://user-images.githubusercontent.com/32230484/35885434-a4377342-0b42-11e8-89f8-a31827500630.png)

Any suggestion? Kind regards!

**Comment by ntamas** [comment] 2018-02-07 11:57
Please post the full output of the `make` step as well as the output of `pip install python-igraph` (not as a screenshot, but as an attachment). The easiest is probably if you upload it to [Pastebin](http://pastebin.com) and then link it here.

**Comment by kc-data** [comment] 2018-02-08 07:48
Hello! 
Thank you for your reply. I have pasted the entire configure log. https://pastebin.com/xiB1FriA

**Comment by ntamas** [comment] 2018-02-08 12:58
Can you post the output of `make` as well as the output of `pip install python-igraph`?

**Comment by kc-data** [comment] 2018-02-08 19:10
Yes. The file is a bit large, so I put the log output.txt on this Google drive: https://drive.google.com/file/d/1fM7-LIxwdnR8lfPpC6kC3UP-EGC9bWYN/view?usp=sharing

**Comment by ntamas** [comment] 2018-02-08 22:52
You are probably hitting [this issue](https://chrisjcameron.github.io/2016/04/27/homebrew_and_anaconda/), which is probably caused by a bug in the libraries shipped with Anaconda Python. (I'm not familiar with the internals, but it seems like some library in Anaconda Python lists `/usr/lib/libiconv.la` as a dependency, but that file does not exist on a stock OS X). The solution is to install igraph's C core via Homebrew, and then force `pip` to explicitly avoid linking to this incorrect library from Anaconda Python.

**Comment by jeremydouglass** [comment] 2018-05-06 16:16
I encountered the same problem (igraph unable to link to or build missing C core) while working with OS X 10.12 and Python2.

The above advice worked for me:

    brew install igraph
    pip -v install python-igraph==0.7.1.post6

This is what success looked like:

    [...]
    ==> Installing igraph
    ==> Downloading https://homebrew.bintray.com/bottles/igraph-0.7.1_6.sierra.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring igraph-0.7.1_6.sierra.bottle.tar.gz
    🍺  /usr/local/Cellar/igraph/0.7.1_6: 85 files, 6MB

    [...]
    Successfully built python-igraph
    Installing collected packages: python-igraph
    Successfully installed python-igraph-0.7.1.post6

**Comment by gchilczuk** [comment] 2018-09-24 22:28
I'm using Ubuntu 18.04 but I encountered the same error. I didn't find a solution here so this is what finally solved my problems:
```sudo apt install build-essential python-dev libxml2 libxml2-de zlib1g-dev```

**Comment by ntamas** [comment] 2020-01-10 10:40
igraph's C core is now downloaded using git submodules, not directly, so this issue is not relevant any more. Closing it.

**Closed by ntamas** 2020-01-10 10:40 UTC
Labels: installation

**Comment by kamblesamadhan** [comment] 2020-02-12 07:44
I am getting the following error on ubuntu 18.04. I tried "sudo apt install build-essential python-dev libxml2 libxml2-dev zlib1g-dev" also but error didn't resolved.

Collecting python-igraph
  Using cached https://files.pythonhosted.org/packages/3a/3b/bb574a95abb019636d2525a2622d7ea94a740ec91b5b65b909d34cf87174/python-igraph-0.8.0.tar.gz
Collecting texttable>=1.6.2 (from python-igraph)
  Using cached https://files.pythonhosted.org/packages/ec/b1/8a1c659ce288bf771d5b1c7cae318ada466f73bd0e16df8d86f27a2a3ee7/texttable-1.6.2-py2.py3-none-any.whl
Building wheels for collected packages: python-igraph
  Running setup.py bdist_wheel for python-igraph ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tvymq7lq/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpe3e7a1nwpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/matching.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/formula.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/version.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/configuration.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/statistics.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/summary.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/__init__.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/datatypes.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/cut.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/utils.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/clustering.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/compat.py -> build/lib.linux-x86_64-3.6/igraph
  copying src/igraph/layout.py -> build/lib.linux-x86_64-3.6/igraph
  creating build/lib.linux-x86_64-3.6/igraph/app
  copying src/igraph/app/shell.py -> build/lib.linux-x86_64-3.6/igraph/app
  copying src/igraph/app/__init__.py -> build/lib.linux-x86_64-3.6/igraph/app
  creating build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/coord.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/metamagic.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/shapes.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/graph.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/text.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/colors.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/__init__.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/utils.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/edge.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  copying src/igraph/drawing/vertex.py -> build/lib.linux-x86_64-3.6/igraph/drawing
  creating build/lib.linux-x86_64-3.6/igraph/remote
  copying src/igraph/remote/gephi.py -> build/lib.linux-x86_64-3.6/igraph/remote
  copying src/igraph/remote/__init__.py -> build/lib.linux-x86_64-3.6/igraph/remote
  Fixing build/lib.linux-x86_64-3.6/igraph/matching.py build/lib.linux-x86_64-3.6/igraph/formula.py build/lib.linux-x86_64-3.6/igraph/version.py build/lib.linux-x86_64-3.6/igraph/configuration.py build/lib.linux-x86_64-3.6/igraph/statistics.py build/lib.linux-x86_64-3.6/igraph/summary.py build/lib.linux-x86_64-3.6/igraph/__init__.py build/lib.linux-x86_64-3.6/igraph/datatypes.py build/lib.linux-x86_64-3.6/igraph/cut.py build/lib.linux-x86_64-3.6/igraph/utils.py build/lib.linux-x86_64-3.6/igraph/clustering.py build/lib.linux-x86_64-3.6/igraph/compat.py build/lib.linux-x86_64-3.6/igraph/layout.py build/lib.linux-x86_64-3.6/igraph/app/shell.py build/lib.linux-x86_64-3.6/igraph/app/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/coord.py build/lib.linux-x86_64-3.6/igraph/drawing/metamagic.py build/lib.linux-x86_64-3.6/igraph/drawing/shapes.py build/lib.linux-x86_64-3.6/igraph/drawing/graph.py build/lib.linux-x86_64-3.6/igraph/drawing/text.py build/lib.linux-x86_64-3.6/igraph/drawing/colors.py build/lib.linux-x86_64-3.6/igraph/drawing/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/utils.py build/lib.linux-x86_64-3.6/igraph/drawing/edge.py build/lib.linux-x86_64-3.6/igraph/drawing/baseclasses.py build/lib.linux-x86_64-3.6/igraph/drawing/vertex.py build/lib.linux-x86_64-3.6/igraph/remote/gephi.py build/lib.linux-x86_64-3.6/igraph/remote/__init__.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  Fixing build/lib.linux-x86_64-3.6/igraph/matching.py build/lib.linux-x86_64-3.6/igraph/formula.py build/lib.linux-x86_64-3.6/igraph/version.py build/lib.linux-x86_64-3.6/igraph/configuration.py build/lib.linux-x86_64-3.6/igraph/statistics.py build/lib.linux-x86_64-3.6/igraph/summary.py build/lib.linux-x86_64-3.6/igraph/__init__.py build/lib.linux-x86_64-3.6/igraph/datatypes.py build/lib.linux-x86_64-3.6/igraph/cut.py build/lib.linux-x86_64-3.6/igraph/utils.py build/lib.linux-x86_64-3.6/igraph/clustering.py build/lib.linux-x86_64-3.6/igraph/compat.py build/lib.linux-x86_64-3.6/igraph/layout.py build/lib.linux-x86_64-3.6/igraph/app/shell.py build/lib.linux-x86_64-3.6/igraph/app/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/coord.py build/lib.linux-x86_64-3.6/igraph/drawing/metamagic.py build/lib.linux-x86_64-3.6/igraph/drawing/shapes.py build/lib.linux-x86_64-3.6/igraph/drawing/graph.py build/lib.linux-x86_64-3.6/igraph/drawing/text.py build/lib.linux-x86_64-3.6/igraph/drawing/colors.py build/lib.linux-x86_64-3.6/igraph/drawing/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/utils.py build/lib.linux-x86_64-3.6/igraph/drawing/edge.py build/lib.linux-x86_64-3.6/igraph/drawing/baseclasses.py build/lib.linux-x86_64-3.6/igraph/drawing/vertex.py build/lib.linux-x86_64-3.6/igraph/remote/gephi.py build/lib.linux-x86_64-3.6/igraph/remote/__init__.py
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  running build_c_core
  We are going to build the C core of igraph.
    Source folder: vendor/source/igraph
    Build folder: vendor/build/igraph
    Install folder: vendor/install/igraph
  
  Bootstrapping igraph...
  Finding out version number/string... fatal: not a git repository: /tmp/pip-build-tvymq7lq/python-igraph/vendor/source/igraph/../../../.git/modules/vendor/source/igraph
  0.8.0-pre+
  libtoolize or glibtoolize not found or not in the path!
  Could not compile the C core of igraph.
  
  
  ----------------------------------------
  Failed building wheel for python-igraph
  Running setup.py clean for python-igraph
Failed to build python-igraph
Installing collected packages: texttable, python-igraph
  Running setup.py install for python-igraph ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tvymq7lq/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s80p2j_8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/matching.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/formula.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/version.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/configuration.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/statistics.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/summary.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/__init__.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/datatypes.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/cut.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/utils.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/clustering.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/compat.py -> build/lib.linux-x86_64-3.6/igraph
    copying src/igraph/layout.py -> build/lib.linux-x86_64-3.6/igraph
    creating build/lib.linux-x86_64-3.6/igraph/app
    copying src/igraph/app/shell.py -> build/lib.linux-x86_64-3.6/igraph/app
    copying src/igraph/app/__init__.py -> build/lib.linux-x86_64-3.6/igraph/app
    creating build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/coord.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/metamagic.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/shapes.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/graph.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/text.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/colors.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/__init__.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/utils.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/edge.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/baseclasses.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    copying src/igraph/drawing/vertex.py -> build/lib.linux-x86_64-3.6/igraph/drawing
    creating build/lib.linux-x86_64-3.6/igraph/remote
    copying src/igraph/remote/gephi.py -> build/lib.linux-x86_64-3.6/igraph/remote
    copying src/igraph/remote/__init__.py -> build/lib.linux-x86_64-3.6/igraph/remote
    Fixing build/lib.linux-x86_64-3.6/igraph/matching.py build/lib.linux-x86_64-3.6/igraph/formula.py build/lib.linux-x86_64-3.6/igraph/version.py build/lib.linux-x86_64-3.6/igraph/configuration.py build/lib.linux-x86_64-3.6/igraph/statistics.py build/lib.linux-x86_64-3.6/igraph/summary.py build/lib.linux-x86_64-3.6/igraph/__init__.py build/lib.linux-x86_64-3.6/igraph/datatypes.py build/lib.linux-x86_64-3.6/igraph/cut.py build/lib.linux-x86_64-3.6/igraph/utils.py build/lib.linux-x86_64-3.6/igraph/clustering.py build/lib.linux-x86_64-3.6/igraph/compat.py build/lib.linux-x86_64-3.6/igraph/layout.py build/lib.linux-x86_64-3.6/igraph/app/shell.py build/lib.linux-x86_64-3.6/igraph/app/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/coord.py build/lib.linux-x86_64-3.6/igraph/drawing/metamagic.py build/lib.linux-x86_64-3.6/igraph/drawing/shapes.py build/lib.linux-x86_64-3.6/igraph/drawing/graph.py build/lib.linux-x86_64-3.6/igraph/drawing/text.py build/lib.linux-x86_64-3.6/igraph/drawing/colors.py build/lib.linux-x86_64-3.6/igraph/drawing/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/utils.py build/lib.linux-x86_64-3.6/igraph/drawing/edge.py build/lib.linux-x86_64-3.6/igraph/drawing/baseclasses.py build/lib.linux-x86_64-3.6/igraph/drawing/vertex.py build/lib.linux-x86_64-3.6/igraph/remote/gephi.py build/lib.linux-x86_64-3.6/igraph/remote/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    Fixing build/lib.linux-x86_64-3.6/igraph/matching.py build/lib.linux-x86_64-3.6/igraph/formula.py build/lib.linux-x86_64-3.6/igraph/version.py build/lib.linux-x86_64-3.6/igraph/configuration.py build/lib.linux-x86_64-3.6/igraph/statistics.py build/lib.linux-x86_64-3.6/igraph/summary.py build/lib.linux-x86_64-3.6/igraph/__init__.py build/lib.linux-x86_64-3.6/igraph/datatypes.py build/lib.linux-x86_64-3.6/igraph/cut.py build/lib.linux-x86_64-3.6/igraph/utils.py build/lib.linux-x86_64-3.6/igraph/clustering.py build/lib.linux-x86_64-3.6/igraph/compat.py build/lib.linux-x86_64-3.6/igraph/layout.py build/lib.linux-x86_64-3.6/igraph/app/shell.py build/lib.linux-x86_64-3.6/igraph/app/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/coord.py build/lib.linux-x86_64-3.6/igraph/drawing/metamagic.py build/lib.linux-x86_64-3.6/igraph/drawing/shapes.py build/lib.linux-x86_64-3.6/igraph/drawing/graph.py build/lib.linux-x86_64-3.6/igraph/drawing/text.py build/lib.linux-x86_64-3.6/igraph/drawing/colors.py build/lib.linux-x86_64-3.6/igraph/drawing/__init__.py build/lib.linux-x86_64-3.6/igraph/drawing/utils.py build/lib.linux-x86_64-3.6/igraph/drawing/edge.py build/lib.linux-x86_64-3.6/igraph/drawing/baseclasses.py build/lib.linux-x86_64-3.6/igraph/drawing/vertex.py build/lib.linux-x86_64-3.6/igraph/remote/gephi.py build/lib.linux-x86_64-3.6/igraph/remote/__init__.py
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    running build_c_core
    We are going to build the C core of igraph.
      Source folder: vendor/source/igraph
      Build folder: vendor/build/igraph
      Install folder: vendor/install/igraph
    
    Bootstrapping igraph...
    Finding out version number/string... fatal: not a git repository: /tmp/pip-build-tvymq7lq/python-igraph/vendor/source/igraph/../../../.git/modules/vendor/source/igraph
    0.8.0-pre+
    libtoolize or glibtoolize not found or not in the path!
    Could not compile the C core of igraph.
    
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tvymq7lq/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s80p2j_8-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-tvymq7lq/python-igraph/

**Comment by vtraag** [comment] 2020-02-12 07:52
@EmilyYanW, your problem is not immediately related to this issue. We have opened a support forum for `igraph`, and you should post your installation problems there: https://igraph.discourse.group.

I believe the problem is quite simple: you should install `libtool`, using `apt-get install libtool`. You might also need to install `bison` , `flex`, `automake` and `autoconf`.

**Comment by ntamas** [comment] 2020-02-12 08:19
Another aspect of the problem is that PyPI now contains precompiled Python wheels for Linux so there shouldn't be a need to compile anything. @kamblesamadhan Could it be the case that `pip` on your machine is outdated and it can't recognize the Python wheels that we have pre-compiled for Linux?

Try updating the `python-pip` or `python3-pip` package on your machine first. If that fails or does not solve the problem, try to install the most up-to-date version of `pip` locally in your home directory by running `pip install --upgrade --user pip` and then use that when running `pip install python-igraph.` It should recognize the pre-built wheel on PyPI and use that.

**Comment by Dvoraak** [comment] 2020-05-23 20:11
After upgrading pip, it worked for me. Thanks!

**Comment by Babi17** [comment] 2020-06-04 09:03
I am getting the following Error at the time of make -

arnab@arnab-Inspiron-3558:~/Downloads/igraph-master$ make
make  all-recursive
make[1]: Entering directory '/home/arnab/Downloads/igraph-master'
Making all in src
make[2]: Entering directory '/home/arnab/Downloads/igraph-master/src'
/bin/bash ../ylwrap foreign-ncol-parser.y y.tab.c foreign-ncol-parser.c y.tab.h `echo foreign-ncol-parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output foreign-ncol-parser.output -- byacc -d 
byacc: e - line 74 of "/home/arnab/Downloads/igraph-master/src/foreign-ncol-parser.y", syntax error
%output="y.tab.c"
^
Makefile:9042: recipe for target 'foreign-ncol-parser.c' failed
make[2]: *** [foreign-ncol-parser.c] Error 1
make[2]: Leaving directory '/home/arnab/Downloads/igraph-master/src'
Makefile:503: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/arnab/Downloads/igraph-master'
Makefile:406: recipe for target 'all' failed
make: *** [all] Error 2

How to resolve?

**Comment by szhorvat** [comment] 2020-06-04 09:25
@Babi17 The issue tracker is reserved for bug reports and feature requests. Please use the forum for support questions: https://igraph.discourse.group/  Be sure to explain what you did precisely (where you got the source code from, what commands you ran from the beginning, etc.)
