### ISSUE TITLE
Efficient all-to-all shortest paths

### ISSUE THREAD

**Issue by cadop** [igraph/python-igraph#246] opened 2019-09-08 19:57 UTC
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Attached is the sample file and code.  Using scipy all shortest paths is around 2x faster than igraph.  Is there something preventing igraph for doing this calculation efficiently? If not, maybe the feature request would be to just use the scipy method in the backend?

[TestCode.zip](https://github.com/igraph/python-igraph/files/3587983/TestCode.zip)

**Comment by ntamas** [comment] 2019-09-09 09:43
Thanks for the report, we'll investigate it.

For sake of reference, here is the heaviest stack trace reported by Instruments.app on macOS:

<img width="304" alt="Screenshot 2019-09-09 at 11 42 44" src="https://user-images.githubusercontent.com/195637/64520712-fecac480-d2f6-11e9-9bb9-6ff31329fd98.png">

**Comment by ntamas** [comment] 2019-09-09 09:55
Some more details:

<img width="599" alt="Screenshot 2019-09-09 at 11 54 11" src="https://user-images.githubusercontent.com/195637/64521671-b6140b00-d2f8-11e9-9869-90f4ee9dfbaf.png">

**Comment by vtraag** [comment] 2019-09-09 10:53
What is the overhead of Python compared to the pure C calculations?

**Comment by ntamas** [comment] 2019-09-09 11:11
Negligible; most of the calculations happen in the C layer. It takes 47.82s on my machine to do the calculation and 1.52s to convert the result matrix back to a Python list-of-lists.

**Comment by ntamas** [comment] 2019-09-09 13:45
For the record: the code sample creates an _undirected_ graph from a SciPy matrix, and there are lots of mutual edges with identical weights in the input. Creating a _directed_ igraph graph instead cuts down the calculation time from ~50 seconds to ~26 seconds, but SciPy takes only 13 seconds on my machine. So I believe the initial code sample posted is wrong, and one needs to set `directed=True` in the igraph Graph constructor in the code sample to observe the reported 2x speed difference.

**Comment by cadop** [comment] 2019-09-09 13:58
sorry about that, I thought the graph gets inferred with construction like that. I don't work in C so I can't contribute that side, but if multi-core will be a feature in the future for igraph, dijkstra all-to-all can be split among the cores used and calculated in parallel, which would also speed it up significantly. 

At least in python it does not take much effort (no need to actually change the dijkstra implementation, its just distributing the number of times it gets called).

**Comment by vtraag** [comment] 2019-09-10 06:54
Hmm, I don't see any difference in runtime when constructing the `Graph` using `directed=True`. Timing of `scipy` is 18.8 and 15.8, timing of `igraph` is 16.2 and 17.0 on my machine. 

@cadop, can you confirm whether you still get results twice as fast for `scipy` compared to `igraph` when using `directed=True` in the `Graph` constructor?

@ntamas, strange to see you do not get the same speed. Is there a difference in optimisation? Perhaps you have debug symbols enabled while comparing the speed of `igraph` to `scipy`?

**Comment by cadop** [comment] 2019-09-10 10:31
Not the large difference anymore, it was the `directed=true` mistake.  Now it is only slightly slower.

**Comment by ntamas** [comment] 2019-09-10 11:07
> if multi-core will be a feature in the future for igraph, dijkstra all-to-all can be split among the cores used

Unfortunately it's not that trivial to do it in the C layer. The core of igraph was designed way before multi-core processors were ubiquitous, so there are a couple of global data structures (like the "error stack") that are not thread-safe. We have a compiler flag that converts these data structures to thread-local, but we haven't tested it very intensively, and you could still be running into problems if two threads modify the same igraph data structure at the same time.

Your best bet is probably to use Python's `multiprocessing` module to split up the computation between multiple, independent Python processes. (Python is not good at multithreading anyway unless you are doing IO-bound things because the Python interpreter itself has a Global Interpreter Lock (GIL) that essentially prevents more than a single thread to run Python code at the same time - that's why you need multiprocessing instead). The problem with `multiprocessing` is then that there is an overhead of launching separate Python processes and sending the graph to every single one of them, so it makes sense only above a certain graph size.

@vtraag I don't think so; I was simply installing `python-igraph` in a Python virtualenv with `pip install git+https://github.com/igraph/python-igraph#egg=python-igraph` and everything was then compiled from scratch. I don't think that `pip` compiles stuff with debug symbols by default. (Plus, I did not get any line number information in Instruments.app when I was profiling so I doubt that there was any debug info included).

**Comment by cadop** [comment] 2019-09-10 11:16
@ntamas yes, that was what i was describing  https://github.com/cadop/dijkstra . That version is also a multiple faster than scipy for the given example.  I was hoping it was also trivial for C so it would be a better experience than relying on a python module to split it.

**Comment by ntamas** [comment] 2019-09-10 11:23
I can imagine that this could be done for selected algorithms like the Dijkstra algorithm manually in igraph's C core by adding OpenMP parallel for directives here and there, but we need to be careful with that; basically we need to ensure that the loop bodies do not touch igraph's error stack and that OpenMP takes care of "sharing" variables appropriately between the threads that it launches.

Right now we are focusing on releasing igraph 0.8.0 in the near future so I don't think we can dedicate any effort to this direction until 0.8.0 is released, but it could be a worthy investment for 0.9.0 or later.

**Comment by vtraag** [comment] 2019-09-10 11:38
@ntamas, strange to see you have this difference in speed still then. Any idea why? If you think there might be a problem somewhere we might keep this issue open, but if not we can maybe close this?

**Comment by ntamas** [comment] 2019-09-10 12:01
Unfortunately I have no idea now; maybe you could try testing the same thing in the same way on your machine to get a second sample?

I was doing this:

```
python3 -m venv venv
venv/bin/pip3 install scipy git+https://github.com/igraph/python-igraph#egg=python-igraph
venv/bin/python3 scipy_vs_igraph.py
```

What is really weird, though, is that the same code in C runs in 13 seconds on my machine instead of 26 seconds (compiled with `clang -O3`); Python's overhead cannot be _that_ much, though (and the profiler clearly shows that the vast majority of time is spent in the C layer). Something weird must be going on with the way `pip` builds the library then.

**Comment by ntamas** [comment] 2019-09-10 12:04
One thing that I have noticed is that the `igraph_i_2wheap_sink` call does not repeat so many times in the heaviest stack trace when I was profiling the C code - it only appears once. I guess that the compiler managed to optimize out the tail recursion (which should be a trivial thing to do), and this optimization is not happening when `pip` compiles the Python interface.

**Comment by ntamas** [comment] 2019-09-10 12:47
Another result: compiling igraph from scratch with `--enable-debug` yields the slow performance observed above (~26 seconds), while it works just fine and the performance is comparable to SciPy when compiled without `--enable-debug`. So I'm pretty sure that `pip install` compiles the C core in some way that prevents certain optimizations from happening. Will investigate further.

**Comment by ntamas** [comment] 2019-09-10 13:49
FUrther investigation reveals that when one installs igraph with `pip install`, the `-g` flag is passed automatically by `setup.py` when it compiles the Python extension. Hopefully there's a way to prevent that.

**Comment by vtraag** [comment] 2019-09-10 19:58
The strange thing is that I now have difficulties building a version of `python-igraph` which is also sufficiently fast. It seems that I accidentally tested using a version of `python-igraph` that was installed from `conda-forge` (I was using an open Python session which apparently was running in a different environment than I thought). 

Even when dynamically linking to the pre-compiled library (without debug symbols) the resulting `python-igraph` package runs relatively slowly, and the `python-igraph` C files are indeed compiled using `-g`. Passing `CFLAGS="-g0"` before running `python setup.py install` does not improve things (suggested implicitly [here](https://stackoverflow.com/questions/13143294/distutils-how-to-disable-including-debug-symbols-when-building-an-extension)). 

I don't quite understand why the build from `conda-forge` does run fast and how that compilation differs from what I do locally.

**Comment by vtraag** [comment] 2019-09-10 20:36
Correction: it is possible to build it correctly. 

For some reason, even without `--enable-debug`, it seems that the `configure` script in the C core `igraph` generates a `Makefile` with `CFLAGS = -g -O2`. Manually changing that to `-O3` and then dynamically linking to the generated library correctly generates a fast working `python-igraph` package. Not sure why `CFLAGS = -g -O2` is set by `configure` though.

**Comment by ntamas** [comment] 2019-09-11 16:13
That's the default setting of `AC_PROG_CC` in `autoconf`; I'll fix it.

**Comment by ntamas** [comment] 2019-09-11 17:12
igraph/igraph@141cc0d843 does the trick I think. With these settings, running `pip install git+https://github.com/igraph/python-igraph#egg=python-igraph` seems to have compiled a "fast" version of igraph where the calculation is only a tad bit slower than SciPy. The difference can probably be attributed to the overhead of conversion between Python and C, plus the fact that we are not using a Fibonacci heap but only an "ordinary" heap.

**Closed by ntamas** 2019-09-11 17:12 UTC

**Comment by vtraag** [comment] 2019-09-15 17:52
@ntamas, it seems that in commit https://github.com/igraph/igraph/commit/141cc0d843 `CXXFLAGS` is set to `-g -O2 -O3` when not using `--enable-debug`. I am not sure if this is actually used anywhere, but perhaps this should also be corrected?

**Comment by ntamas** [comment] 2019-09-16 10:46
Fixed, see above. Thanks for the heads up.
