### ISSUE TITLE
python-igraph function ".triad_census()" returns 0 while R igraph returns 304?

### ISSUE THREAD

**Issue by Marmeladenbrot** [igraph/python-igraph#253] opened 2019-10-16 09:08 UTC
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Python: 3.7.4 x64
OS: Windows 10 Pro x64, no admin rights
WHL file from: https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph

Installed via:
> pip install pandas
> pip install python_igraph-0.7.1.post6-cp37-cp37m-win_amd64.whl

File "total_edges.csv" (71kb): https://uni-duisburg-essen.sciebo.de/s/WLDD4ytkjekVcIL

**Python code:**
```
import pandas as pd
import igraph as ig

df_edges = pd.read_csv("total_edges.csv")
g = ig.Graph.TupleList(df_edges.itertuples(index=False), weights=False).as_directed()
print(g.is_directed())
tc = g.triad_census()
print(tc["030T"])


> True
> 0
```

When I try to ouput tc I get
```
> print(tc)
> TypeError: 'float' object cannot be interpreted as an integer
```

**R code:**
```
library(tidyverse)
library(igraph)

edges <- read_csv("total_edges.csv")
tig <- igraph::graph_from_data_frame(edges) %>% as_tbl_graph
triad_census(tig)

> triad_census(tig)
[1] 56140031   665018    98255    12355      344     1759      399     2577      304        8      323       56      188       55      179       49
```

Both programs should output the same value "304" (when assumed that the R function is the correct one) but the Python version results in "0"?

**Comment by szhorvat** [comment] 2019-10-16 09:23
I have not tested any code, but looking at the docs it appears that you are constructing an *undirected* graph from the list of tuples, then converting it to directed. What you want is to construct a directed graph from the tuples. Try `TupleList( ... , directed = True)`.

**Comment by Marmeladenbrot** [comment] 2019-10-16 09:31
Changed my code to:

```
g = ig.Graph.TupleList(df_edges, directed=True, weights=False)
tc = g.triad_census()
print(tc["030T"])
print(tc)

> True
> 0
> TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by ntamas** [comment] 2019-10-16 09:56
Please show us how `list(df_edges.itertuples(index=False))[:10]` looks like. Chances are that something goes wrong there.

There's no standard way to create a graph from a dataframe, but you don't need `pandas` to read a CSV file. On my machine, the `csv` module from the standard library does the trick:

```python
from igraph import Graph
import csv

reader = csv.reader(open("/Users/tamas/Downloads/total_edges.csv"))
lines = list(reader)[1:]
g = Graph.TupleList(lines, directed=True)
print(str(g.triad_census()))
```

This prints the following:

```
003 : 56140031 | 012 :   665018 | 102 :    98255 | 021D:    12355
021U:      344 | 021C:     1759 | 111D:      399 | 111U:     2577
030T:      304 | 030C:        8 | 201 :      323 | 120D:       56
120U:      188 | 120C:       55 | 210 :      179 | 300 :       49
```

**Comment by Marmeladenbrot** [comment] 2019-10-16 10:14
Result of 
`list(df_edges.itertuples(index=False))[:10]`
 is:

> [Pandas(Source='UC-ry8ngUIJHTMBWeoARZGmA', Target='UCMZDcI3W-aufrexL4IvtywA'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCPOmsF_XgQohcJhdj58zshg'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCgswnTF24kRIcqaZu2nbRSw'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCqFccwdgmRa9sdGANiitySw'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCeIhjvzcngxrmBDGc1XXt1A'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCWiw_19a5Kl4bJGQgpiUtAQ'), Pandas(Source='UC-zK3cJdazy01AKTu8g_amg', Target='UCDHKpha0No-67opv6Md9CVQ'), Pandas(Source='UC05_iIGvXue0sR01JNpRHzw', Target='UCdXZYI27KbVdlVbRybit1og'), Pandas(Source='UC05_iIGvXue0sR01JNpRHzw', Target='UC1M6v6JEQyzTKeINGAaCfnw'), Pandas(Source='UC05_iIGvXue0sR01JNpRHzw', Target='UCXDjKXaS5XG7IKbP8Ft-9Vg')]

**Comment by ntamas** [comment] 2019-10-16 10:20
The problem is that Pandas does to seem to return tuples of source-target pairs, it seems to return something else (some special named tuples). Probably passing `name=None` to `itertuples()` will make it return regular tuples, although I don't have `pandas` on my machine so I cannot say for sure.

**Comment by Marmeladenbrot** [comment] 2019-10-16 10:25
> Probably passing name=None to itertuples() will make it return regular tuples

Tried that, does not work.
But
```
g = ig.Graph.TupleList(df_edges.itertuples(index=False), directed=True)
tc = g.triad_census()
print(tc.t030T)
> 304
```

does. Thanks for the hint.

**Comment by Marmeladenbrot** [comment] 2019-10-16 10:32
By the way, is there a way to "mark" the triads in the graph?

I would like to look which nodes are part of a triad and which aren't to plot them differently (triad = some color, not triad = grey or so). Couldn't find anything in the documentation.

Maybe adding an edge attribute / node attribute (either isPartOfTriad = true or triadPart = A/B/C : False or something).

**Comment by vtraag** [comment] 2019-10-16 11:26
Constructing a graph from a `pandas` dataframe is an open issue #29. It would indeed be good to support this.

**Comment by ntamas** [comment] 2019-10-16 12:14
> By the way, is there a way to "mark" the triads in the graph?

You can create a sample triad that you are looking for with `Graph.Isoclass()` (or manually), and then use `Graph.get_subisomorphisms_lad(triad, induced=True)` to look for induced subgraphs that are isomorphic to your sample triad. E.g., to look for feed-forward loops in some graph `g`:

```
ffl = Graph.Formula("A --> B --> C, A --> C")
result = g.get_subisomorphisms_lad(ffl, induced=True)
```

**Comment by Marmeladenbrot** [comment] 2019-10-16 13:02
If I read Graph.Formula() documentation right this creates a new graph but does not allow me to specify the needed connections / triad type (030T) I want to return for in my already existing graph?

**Comment by ntamas** [comment] 2019-10-18 17:33
> If I read Graph.Formula() documentation right this creates a new graph but does not allow me to specify the needed connections / triad type (030T)

Yes, it does. Just specify your triad with a schematic drawing within the string that you pass to `Graph.Formula`. Actually, the `030T` triad is exactly the feedforward loop that I was using in my example:

`Graph.Formula("A --> B --> C, A --> C")`

Basically it says "take an edge that goes from A to B, another one that goes from B to C, and a third one that goes directly from A to C".

**Comment by Marmeladenbrot** [comment] 2019-10-23 16:06
I thought the parameter inside your Graph.Formula() was pseudo code because it threw an error on my Windows machine. Maybe because of the precompiled igraph C-core for Windows (got precompiled .whl file it from https://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph).

I tried it in WSL Ubuntu (19.04, all packages updated with Python 3.7.5 x64) but I get the same error here:

```
Traceback (most recent call last):
  File "count_triads.py", line 16, in <module>
    ffl = ig.Graph.Formula("A --> B --> C, A --> C")
  File "/usr/lib/python3/dist-packages/igraph/formula.py", line 209, in construct_graph_from_formula
    for start_names, end_names, arrowheads in generate_edges(part):
  File "/usr/lib/python3/dist-packages/igraph/formula.py", line 90, in generate_edges
    raise SyntaxError(msg)
SyntaxError: invalid token found in edge specification: A --> B --> C
```

Is the result under Linux/OSX a different one?

**Comment by davidefiocco** [comment] 2019-10-23 21:24
Looks like you are getting the same error as https://github.com/igraph/python-igraph/issues/235 @Marmeladenbrot. Applying the fix/using latest version of the package may (?) help.

Looks like there's a few relatively recent commits that fix formula parsing here https://github.com/igraph/python-igraph/commits/master/igraph/formula.py

**Comment by Marmeladenbrot** [comment] 2019-10-24 10:13
This looks like a solution. Is there a documentation how to compile igraph from scratch with the master branch and install it on my VM?

Also thanks for the hint with list(tc), works now.

**Comment by ntamas** [comment] 2019-10-24 12:31
`pip install git+https://github.com/igraph/python-igraph` should do the trick. (Of course you need a C compiler and stuff in your VM).

**Comment by Marmeladenbrot** [comment] 2019-10-24 13:42
This looks like a solution. Is there a documentation how to compile igraph from scratch with the master branch and install it on my VM?

Also thanks for the hint with list(tc), works now.

/edit found https://github.com/igraph/python-igraph/issues/157 which gives this working command for a simple source installation, including igraph C-core:

`sudo pip3 install -U git+https://github.com/igraph/python-igraph.git`

This should probably be added [here](https://igraph.org/python/doc/tutorial/install.html#compiling-igraph-from-source) because this section is empty.

Now my script works but .... it throws an error:

```
Traceback (most recent call last):
  File "count_triads.py", line 17, in <module>
    result = g.get_subisomorphisms_lad(ffl, induced=True)
igraph._igraph.InternalError: Error at lad.c:125: LAD functions only work on simple graphs, simplify your graph, Invalid value
```

Since we are deep in igraph territory this should explain it (https://igraph.org/r/doc/simplify.html):

> Simple graphs are graphs which do not contain loop and multiple edges.

Needed to add a

`total_edges = total_edges.drop_duplicates()`

because there were duplicate entries in the 2 files I've used to create the total_edge.csv file.

NOW I get a result that looks like triads. Am I correct in the assumption that the numbers are corresponding to the igraph graph object?

So e.g. my result

> [
>     [23, 32, 33],
>     [23, 33, 34],
>     [24, 33, 190],
>     [24, 33, 86],
>     [24, 33, 71],]

maps to my igraph object

> IGRAPH DN-- 700 1278 --
> + attr: name (v)
> + edges (vertex names):
> 1 UC-ry8ngUIJHTMBWeoARZGmA->UCMZDcI3W-aufrexL4IvtywA,
> 2 UC-zK3cJdazy01AKTu8g_amg->UCPOmsF_XgQohcJhdj58zshg,
> 3 UC-zK3cJdazy01AKTu8g_amg->UCgswnTF24kRIcqaZu2nbRSw,
> 4 UC-zK3cJdazy01AKTu8g_amg->UCqFccwdgmRa9sdGANiitySw,
> 5 UC-zK3cJdazy01AKTu8g_amg->UCeIhjvzcngxrmBDGc1XXt1A,
> 6 UC-zK3cJdazy01AKTu8g_amg->UCWiw_19a5Kl4bJGQgpiUtAQ,
> 7 UC-zK3cJdazy01AKTu8g_amg->UCDHKpha0No-67opv6Md9CVQ,

and so on?

That was a ride .....

**Comment by ntamas** [comment] 2019-10-24 18:25
>  Am I correct in the assumption that the numbers are corresponding to the igraph graph object?
Yes, those are indices into the igraph vertex vector.

Closing this since this is not a bug.

**Closed by ntamas** 2019-10-24 18:25 UTC
